package com.example.yangiliklarwebsaytibackend.entity.enums;

public enum Huquqlar {
    ADDPOST, EDITPOST, EDITMYPOST, READPOST, DELETEPOST, DELETEMYPOST,
    ADDCOMMENT, EDITCOMMENT, EDITMYCOMMENT, READCOMMENT, DELETECOMMENT, DELETEMYCOMMENT,
    ADDROLL, EDITROOL, READROOL, DELETEROOL,
    ADDUSER, EDITUSER, READUSER, DELETEUSER,
    LAVOZIMTAYINLASH, EDITMYINFO
}
